-- MySQL Script generated by MySQL Workbench
-- 03/18/16 23:19:08
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema bus
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema bus
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bus` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `bus` ;

-- -----------------------------------------------------
-- Table `bus`.`bus`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus`.`bus` (
  `bus_id` CHAR(32) NOT NULL COMMENT '',
  `bus_name` VARCHAR(32) NOT NULL COMMENT '',
  `bus_direction` VARCHAR(64) NOT NULL COMMENT '',
  PRIMARY KEY (`bus_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus`.`station`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus`.`station` (
  `station_id` CHAR(32) NOT NULL COMMENT '',
  `station_name` VARCHAR(45) NOT NULL COMMENT '',
  PRIMARY KEY (`station_id`)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bus`.`time`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `bus`.`time` (
  `bus_bus_id` CHAR(32) NOT NULL COMMENT '',
  `station_station_id` CHAR(32) NOT NULL COMMENT '',
  `time_id` CHAR(32) NOT NULL COMMENT '',
  `bus_time_normal` DATETIME NOT NULL COMMENT '',
  `bus_time_special` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`bus_bus_id`, `station_station_id`, `time_id`)  COMMENT '',
  INDEX `fk_bus_has_station_station1_idx` (`station_station_id` ASC)  COMMENT '',
  INDEX `fk_bus_has_station_bus_idx` (`bus_bus_id` ASC)  COMMENT '',
  CONSTRAINT `fk_bus_has_station_bus`
    FOREIGN KEY (`bus_bus_id`)
    REFERENCES `bus`.`bus` (`bus_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_bus_has_station_station1`
    FOREIGN KEY (`station_station_id`)
    REFERENCES `bus`.`station` (`station_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
