package com.kuzonchen.model;

import android.database.sqlite.SQLiteDatabase;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;

import com.kuzonchen.model.Timetable;

import com.kuzonchen.model.TimetableDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig timetableDaoConfig;

    private final TimetableDao timetableDao;

    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        timetableDaoConfig = daoConfigMap.get(TimetableDao.class).clone();
        timetableDaoConfig.initIdentityScope(type);

        timetableDao = new TimetableDao(timetableDaoConfig, this);

        registerDao(Timetable.class, timetableDao);
    }

    public void clear() {
        timetableDaoConfig.getIdentityScope().clear();
    }

    public TimetableDao getTimetableDao() {
        return timetableDao;
    }

}
