package com.kuzonchen.model;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

/**
 * Entity mapped to table "TIMETABLE".
 */
public class Timetable {

	private Long id;
	private String StopName;
	private String StopTime;

	public Timetable() {
	}

	public Timetable(Long id) {
		this.id = id;
	}

	public Timetable(Long id, String StopName, String StopTime) {
		this.id = id;
		this.StopName = StopName;
		this.StopTime = StopTime;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getStopName() {
		return StopName;
	}

	public void setStopName(String StopName) {
		this.StopName = StopName;
	}

	public String getStopTime() {
		return StopTime;
	}

	public void setStopTime(String StopTime) {
		this.StopTime = StopTime;
	}

}
